version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1
anchor-name-do-not-matter: &default-docker # The ampersand is what matters
  docker:
    - image: circleci/node:14
commands:
  say-hello-cmd:
    description: A way to describe the command
    parameters:
      arg1:
        type: string
        default: 'World'
    steps:
      - run: echo Hello <<parameters.arg1>>. This is $CIRCLE_WORKFLOW_ID.
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: 'Say hello'
          command: 'echo Hello, World!'
      - say-hello-cmd:
          arg1: Kelechi
  print_hello:
    <<: *default-docker # This is where we use an alias to reference an anchor
    steps:
      - checkout
      - run:
          name: 'Print Hello'
          command: 'echo Hello'
  print_world:
    <<: *default-docker
    environment:
      MY_NAME: Kelechi
      # CIRCLE_COMPARE_URL: <<pipeline.project.git_url>>/compare/<<pipeline.git.base_revision>>..<<pipeline.git.revision>>
    steps:
      - run:
          name: 'Say World'
          command: 'echo World!'
      - run: echo This is pipeline ID <<pipeline.id>>
      - run: echo $CIRCLE_COMPARE_URL
      - run: echo $CIRCLE_USERNAME
      - run: >
          echo CircleBranch: $CIRCLE_BRANCH
          WorkflowID: $CIRCLE_WORKFLOW_ID
          BuildNumber: $CIRCLE_BUILD_NUM
          PRNumber: $CIRCLE_PR_NUMBER
          SHA: $CIRCLE_SHA2
          CircleCompareURL: $CIRCLE_COMPARE_URL
          Repo: $CIRCLE_REPOSITORY_URL
          Branch: $CIRCLE_BRANCH
      - run: echo $MY_NAME
  save_hello_world_output:
    <<: *default-docker
    steps:
      - run: ls -al /tmp
      - run:
          name: 'Output Hello world'
          command: echo hello world > /tmp/output.txt
      - persist_to_workspace:
          root: /tmp
          paths:
            - output.txt
      - run: ls -al /tmp
  print_output_file:
    <<: *default-docker
    steps:
      - attach_workspace:
          at: /tmp
      - run: ls -al /tmp
      - run:
          name: 'Get output'
          command: cat /tmp/output.txt
      - run: ls -al /tmp
  this-job-will-fail:
    <<: *default-docker
    steps:
      - run: exit 1
  check-failure:
    <<: *default-docker
    steps:
      - run:
          name: failed job
          command: echo Job has FAILED by user
          when: on_fail

workflows:
  welcome-workflow: # this is the name of the workflow
    jobs:
      - welcome/run
      - say-hello
      - print_hello
      - print_world:
          requires:
            - print_hello
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - this-job-will-fail
      - check-failure:
          requires:
            - this-job-will-fail
